server:
  port: 9001
spring:
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: optional:configserver:http://myconfigserver.com
# Eureka Service Registry Port is picked thru config server added to bootstrap.yml which points to the github repo to pick the service registry uri

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      DepartmentService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  # retry:
  #   instances:
  #     DepartmentService:
  #       registerHealthIndicator: true
  #       maxRetryAttempts: 5
  #       waitDuration: 10s
  ratelimiter:
    instances:
      DepartmentService:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
